=== johnnymadrid/testsalesforce/src/main/api/schemas/update.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "contactName": {
      "type": "string"
    },
    "contactTitle": {
      "type": "string"
    },
    "contactEmail": {
      "type": "string"
    },
    "contactPhone": {
      "type": "string"
    },
    "accountName": {
      "type": "string"
    },
    "accountPhone": {
      "type": "string"
    },
    "contactMobile": {
      "type": "string"
    },
    "accountParent": {
      "type": "string"
    },
    "rating": {
      "type": "string"
    },
    "accountNumber": {
      "type": "string"
    },
    "website": {
      "type": "string"
    },
    "accountSite": {
      "type": "string"
    },
    "tickerSymbol": {
      "type": "string"
    },
    "accountType": {
      "type": "string"
    },
    "accountOwnership": {
      "type": "string"
    },
    "industry": {
      "type": "string"
    },
    "noOfEmployees": {
      "type": "string"
    },
    "annualRevenue": {
      "type": "string"
    },
    "currencyRevenue": {
      "type": "string"
    },
    "sicCode": {
      "type": "string"
    },
    "accountBillingNumberStreet": {
      "type": "string"
    },
    "accountBillingStreet": {
      "type": "string"
    },
    "accountBillingCity": {
      "type": "string"
    },
    "accountBillingCountry": {
      "type": "string"
    },
    "accountBillingPostCode": {
      "type": "string"
    },
    "accountShippingNumberStreet": {
      "type": "string"
    },
    "accountShippingStreet": {
      "type": "string"
    },
    "accountShippingCity": {
      "type": "string"
    },
    "accountShippingCountry": {
      "type": "string"
    },
    "accountShippingPostCode": {
      "type": "string"
    },
    "accountCustomerPriority": {
      "type": "string"
    },
    "accountSLA": {
      "type": "string"
    },
    "accountSLAExpirationDate": {
      "type": "string"
    },
    "accountSLASerialNumber": {
      "type": "string"
    },
    "accountNumberOfLocations": {
      "type": "string"
    },
    "accountUpsellOpportunity": {
      "type": "string"
    },
    "accountActive": {
      "type": "string"
    }
  },
  "required": [
    "contactName",
    "contactTitle",
    "contactEmail",
    "contactPhone",
    "accountName",
    "accountPhone",
    "contactMobile",
    "accountParent",
    "rating",
    "accountNumber",
    "website",
    "accountSite",
    "tickerSymbol",
    "accountType",
    "accountOwnership",
    "industry",
    "noOfEmployees",
    "annualRevenue",
    "currencyRevenue",
    "sicCode",
    "accountBillingNumberStreet",
    "accountBillingStreet",
    "accountBillingCity",
    "accountBillingCountry",
    "accountBillingPostCode",
    "accountShippingNumberStreet",
    "accountShippingStreet",
    "accountShippingCity",
    "accountShippingCountry",
    "accountShippingPostCode",
    "accountCustomerPriority",
    "accountSLA",
    "accountSLAExpirationDate",
    "accountSLASerialNumber",
    "accountNumberOfLocations",
    "accountUpsellOpportunity",
    "accountActive"
  ]
}

=== johnnymadrid/testsalesforce/src/main/api/.repository/examples/update.json
{
  "contactName": "Newie",
  "contactTitle": "CFO",
  "contactEmail": "firstname.lastname@company.co.uk",
  "contactPhone": "(512) 757-6000",
  "accountName": "",
  "accountPhone": "(512) 987-1234",
  "contactMobile": "(512) 757-6000",
  "accountParent": "",
  "rating": "Medium",
  "accountNumber": "CD123456",
  "website": "http://private-consulting.com",
  "accountSite": "",
  "tickerSymbol": "EDGE",
  "accountType": "Customer - Direct",
  "accountOwnership": "Private",
  "industry": "Consulting",
  "noOfEmployees": "500,000",
  "annualRevenue": "100,000,000",
  "currencyRevenue": "Â£",
  "sicCode": "9000",
  "accountBillingNumberStreet": "1",
  "accountBillingStreet": "Headstone Rd",
  "accountBillingCity": "Harrow",
  "accountBillingCountry": "United Kingdom",
  "accountBillingPostCode": " HA1 1NL",
  "accountShippingNumberStreet": "31A",
  "accountShippingStreet": "Park Road",
  "accountShippingCity": "London",
  "accountShippingCountry": "United Kingdom",
  "accountShippingPostCode": "E15 3QP",
  "accountCustomerPriority": "High",
  "accountSLA": "Gold",
  "accountSLAExpirationDate": "31/12/2016",
  "accountSLASerialNumber": "7562",
  "accountNumberOfLocations": "2",
  "accountUpsellOpportunity": "Maybe",
  "accountActive": "Yes",
  "accountSLASerialNumber": "(408)326-9000"  
}

=== johnnymadrid/testsalesforce/src/test/resources/sample_data/json_1.json
{
  "contactName": "",
  "contactTitle": "",
  "contactEmail": "firstname.lastname@company.co.uk",
  "contactPhone": "????",
  "accountName": "????",
  "accountPhone": "????",
  "contactMobile": "????",
  "accountParent": "????",
  "rating": "????",
  "accountNumber": "????",
  "website": "????",
  "accountSite": "????",
  "tickerSymbol": "????",
  "accountType": "????",
  "accountOwnership": "????",
  "industry": "????",
  "noOfEmployees": "????",
  "annualRevenue": "????",
  "currencyRevenue": "????",
  "sicCode": "????",
  "accountBillingNumberStreet": "????",
  "accountBillingStreet": "????",
  "accountBillingCity": "????",
  "accountBillingCountry": "????",
  "accountBillingPostCode": "????",
  "accountShippingNumberStreet": "????",
  "accountShippingStreet": "????",
  "accountShippingCity": "????",
  "accountShippingCountry": "????",
  "accountShippingPostCode": "????",
  "accountCustomerPriority": "????",
  "accountSLA": "????",
  "accountSLAExpirationDate": "????",
  "accountSLASerialNumber": "????",
  "accountNumberOfLocations": "????",
  "accountUpsellOpportunity": "????",
  "accountActive": "????"
}
